repos:

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: debug-statements
        language_version: python3

-   repo: https://github.com/psf/black
    rev: 21.11b0
    hooks:
    -   id: black
        args: [--safe, --line-length=100]

# -   repo: https://github.com/PyCQA/bandit
#     rev: 1.7.0
#     hooks:
#     - id: bandit

-   repo: https://github.com/PyCQA/pylint
    rev: v2.11.1
    hooks:
    - id: pylint
      args: ["--disable=E0401", "--disable=W9006", "--rcfile=pylintrc", "--load-plugins=pylint.extensions.docparams"]

-   repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
    -   id: flake8
        args: ["--max-line-length=100"]
        language_version: python3

# -   repo: https://github.com/PyCQA/isort
#     rev: 5.10.1
#     hooks:
#       - id: isort

-   repo: https://github.com/asottile/reorder_python_imports
    rev: v2.6.0
    hooks:
    -   id: reorder-python-imports
        args: [--py37-plus]

-   repo: https://github.com/asottile/pyupgrade
    rev: v2.29.1
    hooks:
    -   id: pyupgrade
        args: [--py37-plus]

# ADD MYPY?
